author: Russell Chapman
description:
title: Iron Snail
baseurl: "/iron-snail"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github: [metadata]
github_username: chpmnrssll
github_repository: iron-snail
github_branch: master

repository: "chpmnrssll/iron-snail"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed
  sass_dir: assets/css
